# config/routes.yaml

controllers:
    resource: ../src/Controller/
    type: attribute

accueil:
    path: /accueil
    controller: 'App\Controller\HomeController::index'
    
inscription:
    path: /inscription
    controller: App\Controller\UtilisateurController::inscription

compte_utilisateur:
    path: /compte
    controller: App\Controller\UtilisateurController::compteUtilisateur

deconnexion:
    path: /deconnexion
    controller: App\Controller\UtilisateurController::deconnexion





