# config/routes.yaml

controllers:
    resource: ../src/Controller/
    type: attribute

connexion:
    path: /connexion
    controller: App\Controller\UtilisateurController::connexion

inscription:
    path: /inscription
    controller: App\Controller\UtilisateurController::inscription

compte_utilisateur:
    path: /compte
    controller: App\Controller\UtilisateurController::compteUtilisateur

deconnexion:
    path: /deconnexion
    controller: App\Controller\UtilisateurController::deconnexion

check_keys:
    path: '/check_keys'
    controller: 'App\Controller\UtilisateurController::checkKeys'




