parameters:
    ewz_recaptcha_site_key: '%env(EWZ_RECAPTCHA_SITE_KEY)%'

# services.yaml

# ...

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    
